### ISSUE TITLE
Revamp to do list

### ISSUE THREAD

**Issue by zorg2044** [zorg2044/BoringCrewServices#1]
Art

- [x] Retexture Capsule at 285px/mm
- [x] Fix capsule rotation
- [x] Toggleable window
- [x] Finish parachute bay
- [x] Make main parachutes with hinge animation
- [x] Make drogue chutes
- [x] Adjust top node design
- [x] Animated NDS lid
- [x] Retexture the other sheet
- [x] Mesh RCS holes for doghouses
- [x] Standalone RS88 abort engines
- [x] make air bags
- [x] Adjustment to Centaur adapter
- [x] PBR conversion

Other stuff

- [x] Add Benjee10 NDS
- [x] Add B9PS and waterfall as dependencies
- [x] New RCS and OMS plumes
- [x] Fix Service module solar panels
- [x] offset COM for reentry apollo style
- [x] updated descriptions, names and search tags

**Comment by BSSSNAG** [comment]
for Other, add some new part descriptions. Because the current ones are Crtl+V from BDB Leo capsule

**Comment by zorg2044** [comment]
Basic functions now feature complete
