### ISSUE TITLE
Connected Living Space support

### ISSUE THREAD

**Issue by zorg2044** [zorg2044/BoringCrewServices#11]

**Comment by EmberSkyMedia** [comment]
As a Patch File this should do it, with the lid closed it's collider should block you, but when open you should be okay.

@PART[B10_NDS]:NEEDS[ConnectedLivingSpace]:FOR[BoringCrewServices, !Benjee10_sharedAssets]
{
  MODULE
	{
		name = ModuleConnectedLivingSpace
		passable = true
	}
}
@PART[BCS_Centauri_CrewCapsule]:NEEDS[ConnectedLivingSpace]:FOR[BoringCrewServices]
{
  MODULE
	{
		name = ModuleConnectedLivingSpace
		passable = true
	}
}

**Comment by zorg2044** [comment]
94808cdb438b7403fad740a0a8452af65995b40d
