### ISSUE TITLE
VABOrganizer support

### ISSUE THREAD

**Issue by zorg2044** [zorg2044/BoringCrewServices#13]

**Comment by EmberSkyMedia** [comment]
@PART[BCS_Centauri_CrewCapsule]:FOR[BoringCrewService]:NEEDS[VABOrganizer]
{
  %VABORGANIZER
  {
    %organizerSubcategory = pods
  }
}
@PART[BCS_Centauri_RCSBlock]:FOR[BoringCrewService]:NEEDS[VABOrganizer]
{
  %VABORGANIZER
  {
    %organizerSubcategory = rcs
  }
}
@PART[BCS_Centauri_ParachuteCover]:FOR[BoringCrewService]:NEEDS[VABOrganizer]
{
  %VABORGANIZER
  {
    %organizerSubcategory = fairing
  }
}
@PART[BCS_Centauri_LAE]:FOR[BoringCrewService]:NEEDS[VABOrganizer]
{
  %VABORGANIZER
  {
    %organizerSubcategory = monoEngines
  }
}
@PART[BCS_Centauri_ServiceModule]:FOR[BoringCrewService]:NEEDS[VABOrganizer]
{
  %VABORGANIZER
  {
    %organizerSubcategory = serviceBays
  }
}
@PART[BCS_CentauriMuo_Adapter]:FOR[BoringCrewService]:NEEDS[VABOrganizer]
{
  %VABORGANIZER
  {
    %organizerSubcategory = adapters
  }
}
@PART[BCS_Centauri_HeatShield]:FOR[BoringCrewService]:NEEDS[VABOrganizer]
{
  %VABORGANIZER
  {
    %organizerSubcategory = heatShields
  }
}
@PART[BCS_Centauri_MainChute|BCS_Centauri_DrogueChutes]:FOR[BoringCrewService]:NEEDS[VABOrganizer]
{
  %VABORGANIZER
  {
    %organizerSubcategory = parachutes
  }
}
@PART[BCS_Centauri_CentreBag]:FOR[BoringCrewService]:NEEDS[VABOrganizer]
{
  %VABORGANIZER
  {
    %organizerSubcategory = deployables
  }
}
@PART[BCS_Centauri_NDS_cover]:FOR[BoringCrewService]:NEEDS[VABOrganizer]
{
  %VABORGANIZER
  {
    %organizerSubcategory = airAccessories
  }
}

**Comment by zorg2044** [comment]
94808cdb438b7403fad740a0a8452af65995b40d
