### ISSUE TITLE
Seperator Skif 2 Nodes?

### ISSUE THREAD

**Issue by EmberSkyMedia** [zorg2044/BoringCrewServices#19]
Not 100% whats going on but its possible to attach your bottom tank to the bottom of the service module rather than the skirt... so when the skirt deploys the tank is still attached to the bottom of the service module despite being attache to the skirt... again there appears to be 2 nodes, the bottom one is correct teh top is not.

Skirt Deployed and Decoupled but the tank remains attached (incorrect)
![screenshot962](https://github.com/user-attachments/assets/dd1de58c-ea14-4ea3-949e-cd5c10f962b5)

Skirt Deloyed but not Yet decoupled, but the tank is now correctly attached (correct)
![screenshot965](https://github.com/user-attachments/assets/abdd1817-0371-46b4-900f-7d1eee62012e)
When the skirt decouples now the tank goes with it.

**Comment by zorg2044** [comment]
there is an additional attach node deep within the SM so you can add additional fuel or even a fuel tank + engine if you toggle off the center solar panel. I expect you attached it to that node accidentally.
