### ISSUE TITLE
Docking Port Mr. - Lid Alignment Peaking

### ISSUE THREAD

**Issue by EmberSkyMedia** [zorg2044/BoringCrewServices#20]
Recommendation: Have a Varient of the Lid that accounts for the Docking Port Mr. for Stock Players who don't use the Benji Docking port. I know you can't cover all variables but Docking Port Mr. and its Main varients is not a stretch.

Docking Port Mr, Compact Mr
![screenshot992](https://github.com/user-attachments/assets/2a51a9bc-b7ff-43bb-b03d-d9ebdbf52c26)
![screenshot991](https://github.com/user-attachments/assets/8b15cdb6-b523-4d88-86b8-2205d84dc5d1)

Modular Mr (it adds parachutes) - I think you can ignore this one, but added for completeness for all the "Mr" ports I have.
![screenshot993](https://github.com/user-attachments/assets/2c2faa51-c782-4688-8cfb-fae504c4c9f2)
![screenshot998](https://github.com/user-attachments/assets/3c1d2ee1-7ea2-4998-b93c-d10ea203fb49)
![screenshot999](https://github.com/user-attachments/assets/0fab5a8c-6e39-43b8-8c7b-abf3d6d3265a)

Solution would be to raise the lid bump by 1150 units (mm?) and design it around the Mr. profile, it will stick under the cover (you can see the edges peaking but in the new lid varient they would be lower down.
![screenshot997](https://github.com/user-attachments/assets/1e39c804-2d80-462b-85e5-b8f312d86fdc)
![screenshot996](https://github.com/user-attachments/assets/a789b016-db56-4175-82c5-708083b59458)

**Comment by EmberSkyMedia** [comment]
![screenshot1001](https://github.com/user-attachments/assets/47dd8a8b-7c44-4dcf-9a8b-90cf2d645d17)
Just Checked, docking works in Orbit with the "Mr" Docking Ports, so its mainly do you want o make a varient for the lid or not.

**Comment by zorg2044** [comment]
Sorry I'm not really interested in dealing with this. A copy of Benjee's port is included after all for the accurate build and if people want to use other ports they can use it without the lid. Starliner has flown without it too (OFT-1)
