### ISSUE TITLE
Indicator Lights / Emissives

### ISSUE THREAD

**Issue by EmberSkyMedia** [zorg2044/BoringCrewServices#23]
Wondering if you want me to add indicator lights for the crew?

---I still need to vet this and change the nub positions, it would be a patch---

//Centauri
@PART[BCS_Centauri_CrewCapsule]:AFTER[BoringCrewService]:NEEDS[IndicatorLights]
{
	!MODEL:HAS[#model[IndicatorLights/Meshes/nubbinLamp]],* { }
	!MODULE[ModuleControllableEmmissive] {}
	!MODULE[ModuleCrewIndicator]{}
	MODEL
	{
	        model = IndicatorLights/Meshes/nubbinLamp
	        position = -0.1, 0.215, -1.28
	        scale = 1, 0.25, 0.5
	        rotation = 0, 180, 0
	}
	MODEL
	{
	        model = IndicatorLights/Meshes/nubbinLamp
	        position = 0.08, 0.215, -1.28
	        scale = 1, 0.25, 0.5
	        rotation = 0, 180, 0
	}
	MODEL
	{
	        model = IndicatorLights/Meshes/nubbinLamp
	        position = -0.1, -0.215, -1.28
	        scale = 1, 0.25, 0.5
	        rotation = 0, 180, 0
	}
	MODEL
	{
	        model = IndicatorLights/Meshes/nubbinLamp
	        position = 0.08, -0.215, -1.28
	        scale = 1, 0.25, 0.5
	        rotation = 0, 180, 0
	}
	MODEL
	{
	        model = IndicatorLights/Meshes/nubbinLamp
	        position = 0.08, -0.215, -1.28
	        scale = 1, 0.25, 0.5
	        rotation = 0, 180, 0
	}
	MODULE
	{
		name = ModuleControllableEmissive
		target = IndicatorLights/Meshes/nubbinLamp:0
		emissiveName = crewController0
	}
	MODULE
	{
		name = ModuleControllableEmissive
		target = IndicatorLights/Meshes/nubbinLamp:1
		emissiveName = crewController1
	}
	MODULE
	{
		name = ModuleControllableEmissive
		target = IndicatorLights/Meshes/nubbinLamp:2
		emissiveName = crewController2
	}
	MODULE
	{
		name = ModuleControllableEmissive
		target = IndicatorLights/Meshes/nubbinLamp:3
		emissiveName = crewController3
	}
	MODULE
	{
		name = ModuleControllableEmissive
		target = IndicatorLights/Meshes/nubbinLamp:4
		emissiveName = crewController4
	}
	MODULE {
		name = ModuleCrewIndicator
	    controllerName = crewController0
		toggleName = indicatorToggle
	}
	
	MODULE {
		name = ModuleCrewIndicator
	    controllerName = crewController1
		toggleName = indicatorToggle
	}
	
	MODULE {
		name = ModuleCrewIndicator
	    controllerName = crewController2
		toggleName = indicatorToggle
	}

	MODULE {
		name = ModuleCrewIndicator
	    controllerName = crewController3
		toggleName = indicatorToggle
	}

	MODULE {
		name = ModuleCrewIndicator
	    controllerName = crewController4
		toggleName = indicatorToggle
	}

}

**Comment by zorg2044** [comment]
Im not too familiar with this mod. This is just adding controllable lights? The nav lights are included and being nav lights they should always be on.

Looking at the config it seems like you're also manually adding light meshes to the model in addition to the existing built in lights?

**Comment by EmberSkyMedia** [comment]
They would add little colour dots on the space craft to indicate ocupancy (colours correlate to profession).
![image](https://github.com/user-attachments/assets/4bb19ae4-c4d8-428c-9dc3-daa4415efae7)

**Comment by zorg2044** [comment]
uh I would rather not tbh.

**Comment by EmberSkyMedia** [comment]
Okay
