### ISSUE TITLE
tune main parachute opening speed

### ISSUE THREAD

**Issue by zorg2044** [zorg2044/BoringCrewServices#24]

**Comment by zorg2044** [comment]
9d64b9eaf676595de761a204cae4221c01c90a1b

Might need to tune the animation itself and not just the module...

**Comment by EmberSkyMedia** [comment]
Wondering if you can have the bar drop when the parachutes are cut?
![image](https://github.com/user-attachments/assets/0cd8f6be-1a10-46a1-830b-d49bdf1dccfc)

**Comment by zorg2044** [comment]
This isn't possible with the parachute module unless @SofieBrink is interested in looking at a custom solution. I suspect it would be quite complicated and would not be worth the effort.

**Comment by SofieBrink** [comment]
maybe a far future thing, too much effort for too little gain to do right now. If you really want it to be retracted again i think repacking the chute should do.

**Comment by EmberSkyMedia** [comment]
Okay, I added the parachutes to connected living space so the handle doesn't get in people's way once deployed.

**Comment by SofieBrink** [comment]
i'm sorry that doesn't make any sense to me, the handle is not attached to a node that would allow kerbals to go through anyways

**Comment by EmberSkyMedia** [comment]
Yeah, early morning brain-fart. I’ll do some testing to ensure things work correctly in all situations.
