### ISSUE TITLE
Balancing for RS88 orbital engine

### ISSUE THREAD

**Issue by zorg2044** [zorg2044/BoringCrewServices#26]
Need to work our appropriate thrust and Isp values based on Bantam engine family documents. Since the entire family was conceptualised across a wide range of thrust levels, the orbital version does not have to be a direct evolution of the abort motor.

(also need to add subtype descriptions)

**Comment by EmberSkyMedia** [comment]
https://ntrs.nasa.gov/api/citations/20050237017/downloads/20050237017.pdf

**Comment by zorg2044** [comment]
This note was more to remind me to check the figures for the vacuum nozzle variant thats included. There were 3 different pressure fed variants in the Bantam family of engines that were conceptualized with 1:100 area ratio nozzles (and one with turbo pumps which isnt relevant).

The standard (abort engine) variant seems mostly in the right ballpark now.
