### ISSUE TITLE
Custom staging stack icons

### ISSUE THREAD

**Issue by SofieBrink** [zorg2044/BoringCrewServices#34]
custom icons for the custom heatshield and airbag modules

**Comment by zorg2044** [comment]
In BDB we tend to use ``stagingIcon = WHEEL`` for odd utility decouplers like this (Mercury heatshield and airbag etc). we can probably use that in the interim until we get custom icons?

**Comment by SofieBrink** [comment]
> In BDB we tend to use `stagingIcon = WHEEL` for odd utility decouplers like this (Mercury heatshield and airbag etc). we can probably use that in the interim until we get custom icons?

They currently use the game's mystery icon, it'd require code changes to change this since the modules are both already looking for the respective texture files, not finding them and using the mystery one.

**Comment by EmberSkyMedia** [comment]
![DropShield](https://github.com/user-attachments/assets/c0f010b8-c0f4-4f60-bfee-06b31602647c)
![ExpandAirBags](https://github.com/user-attachments/assets/f344a012-80cd-4925-aa1b-b4d99bc31eb8)

**Comment by SofieBrink** [comment]
@EmberSkyMedia Oh i really like those! there's some really minor tweaks i'd ask for if you're up for those.

- Making the heatshield the same thickness all the way around
- Making the outer airbags be rotated relative to the normal of the capsule bottom (right now they kinda clip through the capsule near the edges)
- Making the center airbag the same size as the outer ones

They should be named `BCS_JettisionIcon.png` and `BCS_AirbagIcon.png` and put in an `Icons` folder inside the BCS gamedata folder, if you do that they should also be loaded ingame.

If your pull request system works again and you're able to submit the files, please export them (or convert them to) `.truecolor` format. this prevents them from getting crushed by the game's png compressor on load.

**Comment by EmberSkyMedia** [comment]
@SofieBrink would these work?
![BSC_AirBagIcon](https://github.com/user-attachments/assets/2a05d7b2-7b48-4933-bf17-eca51a8ece16)
![BSC_JettisonIcon](https://github.com/user-attachments/assets/f7ffaaed-42eb-4216-abda-0cf174a5eb17)

**Comment by SofieBrink** [comment]
Ah I'm sorry for the wait @EmberSkyMedia , thought i'd already responded to this.
I'd be very happy with these icons, would have to have a quick look how they look ingame just to make sure there's no issues. 

@zorg2044  @DylanSemrau
What do you guys think?

Ps. Teensy tiny nitpick, it looks like you may have accidentally clicked the brush here at the bottom of the heatshield? 
![image](https://github.com/user-attachments/assets/8ac389c9-1c87-499f-bcb5-bef02a6a3267)

**Comment by EmberSkyMedia** [comment]
Update Per Nitpick Error

![BSC_JettisonIcon](https://github.com/user-attachments/assets/f8ae533f-eef5-4b01-a35b-033c99297d08)


> Ah I'm sorry for the wait @EmberSkyMedia , thought i'd already responded to this. I'd be very happy with these icons, would have to have a quick look how they look ingame just to make sure there's no issues.
> 
> @zorg2044 @DylanSemrau What do you guys think?
> 
> Ps. Teensy tiny nitpick, it looks like you may have accidentally clicked the brush here at the bottom of the heatshield? ![image](https://private-user-images.githubusercontent.com/63377159/378758985-8ac389c9-1c87-499f-bcb5-bef02a6a3267.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3OTk5NjUsIm5iZiI6MTcyOTc5OTY2NSwicGF0aCI6Ii82MzM3NzE1OS8zNzg3NTg5ODUtOGFjMzg5YzktMWM4Ny00OTlmLWJjYjUtYmVmMDJhNmEzMjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDE5NTQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ODI2NjE3NmQ0ODRmYTdhMWVjNzdjMmY1ODQ0MjcyYzA0ZDkyMGY3OTQ1ODcxZDU5NGVjZmE0Yzg4ZGRkNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nCCI7VaGl9FjdjqghlXdeodiIAuZvTJ-aLZZLFctaw8)

**Comment by SofieBrink** [comment]
> Update Per Nitpick Erro

Fantastic, would you be able/willing to get these ingame and pr them or would you prefer if i did that for you?

**Comment by zorg2044** [comment]
![image](https://github.com/user-attachments/assets/b565bdf0-370c-4214-b825-e014f1556e94)

I think the heatshield one looked messy in game due to the small scale. I removed the little lines and made the shield solid. Looks pretty good I think. Thanks again for making these @EmberSkyMedia 

![image](https://github.com/user-attachments/assets/becdcbfa-ae39-4962-850f-df1037b39cfc)


Im just gonna push these.
