### ISSUE TITLE
Capsule RCS Don't Work

### ISSUE THREAD

**Issue by EmberSkyMedia** [zorg2044/BoringCrewServices#38]
There is Monopropellant left but they don't work (eject the service module before you expend all the Monopropellant via the dog houses do work and you'll see you don't have RCS on the capsule itself).
Also the Reaction Wheels are crazy strong...

**Comment by zorg2044** [comment]
Did you enable the RCS module? I have it set to disabled by default as its only meant to be used when its time for reentry.

I'll take a look at the reaction wheels
