### ISSUE TITLE
Texture Variants

### ISSUE THREAD

**Issue by zorg2044** [zorg2044/BoringCrewServices#43]
Variants

- [x] Default blue grey blankets
- [x] White blankets
- [x] White painted
- [x] Orion Shiny (with tile outlines)
- [x] Orion Black Tiles

**Comment by EmberSkyMedia** [comment]
Can the BCS logo also be used by conform decals or nebula decals seperately from the craft?

**Comment by zorg2044** [comment]
> Can the BCS logo also be used by conform decals or nebula decals seperately from the craft?

I have decided not to do full realistic texture anymore. Instead decals will be provided as per https://github.com/zorg2044/BoringCrewServices/issues/44

This will contain Boeing and BCS logos. Right now just Boeing while Im working on BCS logos.

**Comment by zorg2044** [comment]
37925874965558762d01555f0e9198c74c0e55fc
