### ISSUE TITLE
Drogue parachute altitude slider doesn't go past 5000

### ISSUE THREAD

**Issue by psvmsa** [zorg2044/BoringCrewServices#54]
Whenever the drogue is placed in the VAB, it has an altitude value of 7000, but then dragging the slider makes it so the value cannot go above 5000. Or is this a hardcoded slider max from stock that can't be changed?

**Comment by zorg2044** [comment]
It is indeed a limitation of the stock module. We can set the default in config out of the slider range but thats it.
