### ISSUE TITLE
Capsule decouplers don't have decoupler functionality

### ISSUE THREAD

**Issue by marxman28** [zorg2044/BoringCrewServices#57]
I guess in true Boeing fashion, this thing doesn't work properly. The decoupler parts don't have anything that indicates that they're actually decouplers in their info window—no decoupler force, no decoupler action in the PAW or within the AGs, nothing.
![image](https://github.com/user-attachments/assets/6a1fde42-bf3b-458f-8478-338bcfae9e54)
![image](https://github.com/user-attachments/assets/1e181f86-2af3-4e7d-b527-ff0d82a381cd)
![image](https://github.com/user-attachments/assets/ad807eca-e585-4bcb-af0c-5be818b71a6d)

**Comment by zorg2044** [comment]
Did you install all the required dependencies? In particular Animated Decouplers??
