### ISSUE TITLE
Balancing

### ISSUE THREAD

**Issue by zorg2044** [zorg2044/BoringCrewServices#7]
- [x] Mass balance
- [x] Propellant load and total Dv
- [x] Abort engine thrust
- [x] Cost
- [x] tech tree placement
- [x] Solar panel output

**Comment by EmberSkyMedia** [comment]
Looking at all my loaded mods and and the wild pricing (Sorry I don't have BDB installed) here are the numbers I came up with:

Costs (Stock)
Capsule - $6100
Parachute - $1100
Drogue - $450
Heat Shield - $800
Service Module - $1500
RCS Thruster Blocks - $650 each

Cover - Unchanged
Lid - Unchanged
Airbag - Unchanged
Abort Engines - Unchanged
Skirt - Unchanged
